services:
  k:
    # image: runtimeverificationinc/kframework-k:ubuntu-noble-7.1.212
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src:/app
    working_dir: /app
